# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Random Thoughts' 
tagline:          'Thoughts on Programming'
description:      'Jestan Nirojans blog ...'
url:              http://jestan.github.io
baseurl:          '/index.html'
paginate:         5

author:
  name:           'Jestan Nirojan'
  url:            https://twitter.com/JestanNirojan

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jestan/jestan.github.io
